common:
  msg_source: 1                                         #0: not use Lidar
                                                        #1: packet message comes from online Lidar
                                                        #2: packet message comes from ROS or ROS2
                                                        #3: packet message comes from Pcap file
  send_packet_ros: false                                #true: Send packets through ROS or ROS2(Used to record packet)
  send_point_cloud_ros: true                            #true: Send point cloud through ROS or ROS2
lidar:
  - driver:
      lidar_type: RSHELIOS_16P             #LiDAR type - RS16, RS32, RSBP, RSBPV4, RSHELIOS, RSHELIOS_16P, RS128, RS80, RS48, RSP128, RSP80, RSP48, 
                                   #             RSM1, RSM1_JUMBO, RSM2, RSE1
      msop_port: 9966             #Msop port of lidar
      difop_port: 8877             #Difop port of lidar
      start_angle: 0               #Start angle of point cloud
      end_angle: 360               #End angle of point cloud 
      wait_for_difop: true
      min_distance: 0.2            #Minimum distance of point cloud
      max_distance: 200            #Maximum distance of point cloud
      use_lidar_clock: false       #True--Use the lidar clock as the message timestamp
                                   #False-- Use the system clock as the timestamp
      pcap_path: /home/robosense/lidar.pcap #The path of pcap file
    ros:
      ros_frame_id: velodyne                           #Frame id of packet message and point cloud message
      ros_recv_packet_topic: /up/rslidar_packets          #Topic used to receive lidar packets from ROS
      ros_send_packet_topic: /up/rslidar_packets          #Topic used to send lidar packets through ROS
      ros_send_point_cloud_topic: /points_up     #Topic used to send point cloud through ROS
    proto:
      point_cloud_recv_port: 60021                    
      point_cloud_send_port: 60021                     
      msop_recv_port: 60022                
      msop_send_port: 60022
      difop_recv_port: 60023                      
      difop_send_port: 60023       
      point_cloud_send_ip: 127.0.0.1                 
      packet_send_ip: 127.0.0.1

  - driver:
      lidar_type: RSBP           
      msop_port: 6699            
      difop_port: 7788            
      start_angle: 0              
      end_angle: 360               
      min_distance: 0.2            
      max_distance: 200
      use_lidar_clock: false        
    ros:
      ros_frame_id: velodyne_front           
      ros_recv_packet_topic: /front/rslidar_packets    
      ros_send_packet_topic: /front/rslidar_packets    
      ros_send_point_cloud_topic: /points_front  
    proto:
      point_cloud_recv_port: 60027                    
      point_cloud_send_port: 60027                     
      msop_recv_port: 60028  
      msop_send_port: 60028
      difop_recv_port: 60029                      
      difop_send_port: 60029       
      point_cloud_send_ip: 127.0.0.1                   
      packet_send_ip: 127.0.0.1 

