// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: visualization.proto
#ifndef GRPC_visualization_2eproto__INCLUDED
#define GRPC_visualization_2eproto__INCLUDED

#include "visualization.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace visualization {

class Visualizer final {
 public:
  static constexpr char const* service_full_name() {
    return "visualization.Visualizer";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status DataSend(::grpc::ClientContext* context, const ::visualization::Frame& request, ::visualization::Reply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::visualization::Reply>> AsyncDataSend(::grpc::ClientContext* context, const ::visualization::Frame& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::visualization::Reply>>(AsyncDataSendRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::visualization::Reply>> PrepareAsyncDataSend(::grpc::ClientContext* context, const ::visualization::Frame& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::visualization::Reply>>(PrepareAsyncDataSendRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void DataSend(::grpc::ClientContext* context, const ::visualization::Frame* request, ::visualization::Reply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void DataSend(::grpc::ClientContext* context, const ::visualization::Frame* request, ::visualization::Reply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::visualization::Reply>* AsyncDataSendRaw(::grpc::ClientContext* context, const ::visualization::Frame& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::visualization::Reply>* PrepareAsyncDataSendRaw(::grpc::ClientContext* context, const ::visualization::Frame& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status DataSend(::grpc::ClientContext* context, const ::visualization::Frame& request, ::visualization::Reply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::visualization::Reply>> AsyncDataSend(::grpc::ClientContext* context, const ::visualization::Frame& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::visualization::Reply>>(AsyncDataSendRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::visualization::Reply>> PrepareAsyncDataSend(::grpc::ClientContext* context, const ::visualization::Frame& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::visualization::Reply>>(PrepareAsyncDataSendRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void DataSend(::grpc::ClientContext* context, const ::visualization::Frame* request, ::visualization::Reply* response, std::function<void(::grpc::Status)>) override;
      void DataSend(::grpc::ClientContext* context, const ::visualization::Frame* request, ::visualization::Reply* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::visualization::Reply>* AsyncDataSendRaw(::grpc::ClientContext* context, const ::visualization::Frame& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::visualization::Reply>* PrepareAsyncDataSendRaw(::grpc::ClientContext* context, const ::visualization::Frame& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_DataSend_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status DataSend(::grpc::ServerContext* context, const ::visualization::Frame* request, ::visualization::Reply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_DataSend : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_DataSend() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_DataSend() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DataSend(::grpc::ServerContext* /*context*/, const ::visualization::Frame* /*request*/, ::visualization::Reply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDataSend(::grpc::ServerContext* context, ::visualization::Frame* request, ::grpc::ServerAsyncResponseWriter< ::visualization::Reply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_DataSend<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_DataSend : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_DataSend() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::visualization::Frame, ::visualization::Reply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::visualization::Frame* request, ::visualization::Reply* response) { return this->DataSend(context, request, response); }));}
    void SetMessageAllocatorFor_DataSend(
        ::grpc::MessageAllocator< ::visualization::Frame, ::visualization::Reply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::visualization::Frame, ::visualization::Reply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_DataSend() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DataSend(::grpc::ServerContext* /*context*/, const ::visualization::Frame* /*request*/, ::visualization::Reply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* DataSend(
      ::grpc::CallbackServerContext* /*context*/, const ::visualization::Frame* /*request*/, ::visualization::Reply* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_DataSend<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_DataSend : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_DataSend() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_DataSend() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DataSend(::grpc::ServerContext* /*context*/, const ::visualization::Frame* /*request*/, ::visualization::Reply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_DataSend : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_DataSend() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_DataSend() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DataSend(::grpc::ServerContext* /*context*/, const ::visualization::Frame* /*request*/, ::visualization::Reply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDataSend(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_DataSend : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_DataSend() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->DataSend(context, request, response); }));
    }
    ~WithRawCallbackMethod_DataSend() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DataSend(::grpc::ServerContext* /*context*/, const ::visualization::Frame* /*request*/, ::visualization::Reply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* DataSend(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_DataSend : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_DataSend() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::visualization::Frame, ::visualization::Reply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::visualization::Frame, ::visualization::Reply>* streamer) {
                       return this->StreamedDataSend(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_DataSend() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status DataSend(::grpc::ServerContext* /*context*/, const ::visualization::Frame* /*request*/, ::visualization::Reply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedDataSend(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::visualization::Frame,::visualization::Reply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_DataSend<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_DataSend<Service > StreamedService;
};

}  // namespace visualization


#endif  // GRPC_visualization_2eproto__INCLUDED
