// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: visualization.proto

#include "visualization.pb.h"
#include "visualization.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace visualization {

static const char* Visualizer_method_names[] = {
  "/visualization.Visualizer/DataSend",
};

std::unique_ptr< Visualizer::Stub> Visualizer::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Visualizer::Stub> stub(new Visualizer::Stub(channel, options));
  return stub;
}

Visualizer::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_DataSend_(Visualizer_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Visualizer::Stub::DataSend(::grpc::ClientContext* context, const ::visualization::Frame& request, ::visualization::Reply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::visualization::Frame, ::visualization::Reply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_DataSend_, context, request, response);
}

void Visualizer::Stub::async::DataSend(::grpc::ClientContext* context, const ::visualization::Frame* request, ::visualization::Reply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::visualization::Frame, ::visualization::Reply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DataSend_, context, request, response, std::move(f));
}

void Visualizer::Stub::async::DataSend(::grpc::ClientContext* context, const ::visualization::Frame* request, ::visualization::Reply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DataSend_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::visualization::Reply>* Visualizer::Stub::PrepareAsyncDataSendRaw(::grpc::ClientContext* context, const ::visualization::Frame& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::visualization::Reply, ::visualization::Frame, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_DataSend_, context, request);
}

::grpc::ClientAsyncResponseReader< ::visualization::Reply>* Visualizer::Stub::AsyncDataSendRaw(::grpc::ClientContext* context, const ::visualization::Frame& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncDataSendRaw(context, request, cq);
  result->StartCall();
  return result;
}

Visualizer::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Visualizer_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Visualizer::Service, ::visualization::Frame, ::visualization::Reply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Visualizer::Service* service,
             ::grpc::ServerContext* ctx,
             const ::visualization::Frame* req,
             ::visualization::Reply* resp) {
               return service->DataSend(ctx, req, resp);
             }, this)));
}

Visualizer::Service::~Service() {
}

::grpc::Status Visualizer::Service::DataSend(::grpc::ServerContext* context, const ::visualization::Frame* request, ::visualization::Reply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace visualization

